import QRCode from "qrcode";
import {
  WHATSAPP_BOOKING_URL,
  ZONNEBANK_SLUGS,
  zonnebankBookingUrl,
} from "./whatsapp";

/**
 * Renders a WhatsApp booking QR as an SVG string.
 *
 * A QR code is baked data, not a link: the URL is woven into the module
 * pattern, so every distinct booking message needs its own code. These are
 * generated by `npm run qr:generate` and committed as assets — see
 * `qr-svg.test.ts`, which regenerates them and fails the suite if a committed
 * file has drifted away from the URL it is supposed to encode.
 *
 * The WhatsApp glyph in the middle is what tells a visitor where the code
 * leads before they read a word. It works because error correction level H
 * makes ~30% of the modules redundant; the knockout below stays far under
 * that budget.
 */

// Lifted verbatim from src/images/whatsapp.svg (viewBox 0 0 18 18).
const WHATSAPP_GLYPH =
  "M8.97451 0C4.06925 0 0.076474 3.99225 0.0743931 8.89908C0.0738728 10.4676 0.483815 11.9986 1.2626 13.3481L0 17.9605L4.71798 16.7228C6.01803 17.4319 7.48145 17.8054 8.97087 17.806H8.97451C13.8792 17.806 17.872 13.8132 17.8741 8.90636C17.8751 6.52838 16.9502 4.29243 15.2698 2.61052C13.5895 0.928093 11.3551 0.00104046 8.97451 0ZM8.97451 16.303H8.97139C7.64428 16.303 6.34214 15.9456 5.20647 15.2719L4.93647 15.1117L2.13711 15.8462L2.88416 13.1166L2.70832 12.8367C1.96803 11.6589 1.57682 10.2975 1.57734 8.90012C1.5789 4.8215 4.89746 1.50347 8.97763 1.50347C10.9535 1.50399 12.8107 2.27445 14.207 3.67283C15.6038 5.07069 16.3722 6.92948 16.3717 8.90584C16.3701 12.9845 13.0516 16.303 8.97451 16.303ZM13.0318 10.7631C12.8097 10.6517 11.7161 10.1138 11.5122 10.0394C11.3083 9.96503 11.16 9.92809 11.0117 10.1508C10.8635 10.3734 10.4374 10.8744 10.3079 11.0227C10.1783 11.1714 10.0483 11.1897 9.82613 11.0783C9.60399 10.967 8.88711 10.7318 8.03809 9.97439C7.37688 9.38497 6.93052 8.65665 6.80098 8.43399C6.67145 8.21133 6.78694 8.09116 6.89879 7.98035C6.99867 7.88098 7.12093 7.72075 7.23225 7.59069C7.34358 7.46064 7.38052 7.36804 7.45439 7.21925C7.52827 7.07098 7.49133 6.94093 7.43566 6.8296C7.38 6.71827 6.9352 5.6237 6.75 5.17838C6.56948 4.74503 6.38636 4.80329 6.24954 4.79653C6.12 4.78977 5.97173 4.78873 5.82347 4.78873C5.6752 4.78873 5.43434 4.84439 5.2304 5.06705C5.02647 5.28971 4.45214 5.82763 4.45214 6.9222C4.45214 8.01676 5.24913 9.07439 5.35994 9.22266C5.47127 9.37092 6.92792 11.6173 9.15867 12.5802C9.68931 12.8091 10.1034 12.946 10.4265 13.0484C10.9592 13.2175 11.444 13.1936 11.8269 13.1364C12.254 13.0724 13.1426 12.5984 13.3278 12.0787C13.513 11.5595 13.513 11.1142 13.4573 11.0211C13.4017 10.9285 13.2534 10.8728 13.0313 10.7615L13.0318 10.7631Z";

/** Matches the viewBox of the hand-made asset these replaced. */
const SIZE = 1125;
/** Quiet zone in modules. Four is the spec minimum; less and scanners struggle. */
const MARGIN = 4;
/**
 * Knockout width in modules. Snapped to whole modules so its edges land on
 * module boundaries instead of shaving pixels off the neighbours, which is
 * what makes logo overlays flaky. At 15 it covers ~8% of the dark modules.
 */
const KNOCKOUT_MODULES = 15;
/** The glyph leaves a white ring inside the knockout so it reads as one mark. */
const GLYPH_RATIO = 0.72;
/**
 * Level Q keeps 25% of the modules redundant — roughly three times what the
 * knockout spends. Level H buys slack we have no use for at the price of a
 * denser grid: the per-bank URLs push H to 65x65, where a module is under 4px
 * at the size these are shown and phones start to struggle. Q lands at 57x57.
 * Headroom for dirt and creases matters for a printed code, not one on screen.
 */
const ERROR_CORRECTION = "Q" as const;
/** Refuse to emit a code that eats more redundancy than level Q can spare. */
const MAX_COVERAGE = 0.15;

/**
 * Every QR the site ships, and the URL each one must encode. The generator
 * script writes these files; the test reads the same list back and compares.
 * Neither one owns the list, so they cannot disagree about what exists.
 */
export const QR_TARGETS: { file: string; url: string }[] = [
  { file: "src/images/qr/algemeen.svg", url: WHATSAPP_BOOKING_URL },
  ...ZONNEBANK_SLUGS.map((slug) => ({
    file: `src/images/qr/${slug}.svg`,
    url: zonnebankBookingUrl(slug),
  })),
];

export function renderQrSvg(url: string): string {
  const qr = QRCode.create(url, { errorCorrectionLevel: ERROR_CORRECTION });
  const count = qr.modules.size;
  const data = qr.modules.data;
  const scale = SIZE / (count + MARGIN * 2);

  const start = Math.floor((count - KNOCKOUT_MODULES) / 2);
  const end = start + KNOCKOUT_MODULES;

  let dark = 0;
  let covered = 0;
  let path = "";

  for (let row = 0; row < count; row++) {
    for (let col = 0; col < count; col++) {
      if (!data[row * count + col]) continue;
      dark++;
      if (row >= start && row < end && col >= start && col < end) {
        covered++;
        continue; // hidden under the knockout, no point drawing it
      }
      const x = ((col + MARGIN) * scale).toFixed(2);
      const y = ((row + MARGIN) * scale).toFixed(2);
      const s = scale.toFixed(2);
      path += `M${x} ${y}h${s}v${s}h-${s}z`;
    }
  }

  const coverage = covered / dark;
  if (coverage > MAX_COVERAGE) {
    throw new Error(
      `QR knockout covers ${(coverage * 100).toFixed(1)}% of dark modules, over the ${MAX_COVERAGE * 100}% ceiling. Shrink KNOCKOUT_MODULES.`
    );
  }

  const koSize = KNOCKOUT_MODULES * scale;
  const koOffset = (start + MARGIN) * scale;
  const glyphBox = koSize * GLYPH_RATIO;
  const glyphOffset = koOffset + (koSize - glyphBox) / 2;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">
  <rect width="${SIZE}" height="${SIZE}" fill="#FFFFFF"/>
  <path d="${path}" fill="#000000"/>
  <rect x="${koOffset.toFixed(2)}" y="${koOffset.toFixed(2)}" width="${koSize.toFixed(2)}" height="${koSize.toFixed(2)}" rx="${(koSize * 0.16).toFixed(2)}" fill="#FFFFFF"/>
  <g transform="translate(${glyphOffset.toFixed(2)} ${glyphOffset.toFixed(2)}) scale(${(glyphBox / 18).toFixed(4)})"><path d="${WHATSAPP_GLYPH}" fill="#000000"/></g>
</svg>
`;
}
