import type { StaticImageData } from "next/image";
import prestige1600 from "@/images/banken/Ergoline-Prestige-1600.webp";
import blueVision from "@/images/banken/Ergoline-Blue-Vision.webp";
import affinity600 from "@/images/banken/Ergoline-600-v2.webp";
import ergoline700 from "@/images/banken/Ergoline-770.webp";
import qrPrestige1600 from "@/images/qr/ergoline-prestige-1600.svg";
import qr770Medium from "@/images/qr/ergoline-770-medium.svg";
import qrBlueVision from "@/images/qr/ergoline-blue-vision.svg";
import qr600Light from "@/images/qr/ergoline-600-light.svg";
import {
  ZONNEBANK_BOOKINGS,
  zonnebankBookingUrl,
  type ZonnebankSlug,
} from "@/lib/whatsapp";

export type Zonnebank = {
  slug: ZonnebankSlug;
  image: StaticImageData;
  imageQuality?: number;
  /**
   * Overrides DESKTOP_FOCUS in ZonnebankMedia for a bank whose shot sits
   * differently in its frame. Must be written out as a full literal class —
   * Tailwind's scanner reads source text, so a value built at runtime
   * generates no CSS.
   */
  desktopFocus?: string;
  mobileVideo: string;
  desktopVideo?: string;
  alt: string;
  title: string;
  tag?: string;
  description: string[];
  minuten: string;
  prijs: string;
  whatsappUrl: string;
  qrCode: StaticImageData;
};

/**
 * The QR each bank's desktop overlay shows. Generated by `npm run qr:generate`
 * from the same slug that builds the WhatsApp link, so a code can never end up
 * on the wrong bank.
 */
const QR_CODES: Record<ZonnebankSlug, StaticImageData> = {
  "ergoline-prestige-1600": qrPrestige1600,
  "ergoline-770-medium": qr770Medium,
  "ergoline-blue-vision": qrBlueVision,
  "ergoline-600-light": qr600Light,
};

/**
 * Title, booking link and QR all follow from `slug`, so they cannot drift
 * apart: rename a bank in `whatsapp.ts` and the heading, the prefilled message
 * and the code all change together.
 */
type ZonnebankInput = Omit<Zonnebank, "title" | "whatsappUrl" | "qrCode">;

const BANKEN: ZonnebankInput[] = [
  {
    slug: "ergoline-prestige-1600",
    image: prestige1600,
    mobileVideo: "/videos/zonnebanken/prestige-1600-toggle-mobile.mp4?v=10",
    desktopVideo: "/videos/zonnebanken/prestige-1600-toggle-desktop.mp4?v=8",
    alt: "Ergoline Prestige 1600 zonnebad",
    tag: "2 banken",
    description: [
      "Het rode Beauty Light stimuleert de doorbloeding van je huid, zodat je kleur dieper wordt en je huid verzorgd blijft.",
      "Met Personal Sunstyle stel je de intensiteit zelf in: sensitive als je huid rustig wil beginnen, medium of intensive voor meer kracht.",
    ],
    minuten: "20 min",
    prijs: "18,00",
  },
  {
    slug: "ergoline-770-medium",
    image: ergoline700,
    mobileVideo: "/videos/zonnebanken/ergoline-770-toggle-mobile.mp4?v=10",
    desktopVideo: "/videos/zonnebanken/ergoline-770-toggle-desktop.mp4?v=8",
    alt: "Ergoline 770 Medium zonnebad",
    description: [
      "Het Dynamic Power systeem houdt de intensiteit je hele sessie constant, zo wordt je kleur overal even egaal opgebouwd.",
      "48 lampen en verder geen extra's. Fijn als je al weet hoe je huid reageert en gewoon een stevige, betrouwbare sessie wil.",
    ],
    minuten: "20 min",
    prijs: "14,00",
  },
  {
    slug: "ergoline-blue-vision",
    image: blueVision,
    imageQuality: 90,
    mobileVideo: "/videos/zonnebanken/blue-vision-toggle-mobile.mp4?v=10",
    desktopVideo: "/videos/zonnebanken/blue-vision-toggle-desktop.mp4?v=8",
    alt: "Ergoline Blue Vision zonnebad",
    tag: "2 banken",
    description: [
      "Het blauwe licht activeert de pigmentcellen in je huid al voor het zonnen. Je kleur komt daardoor sneller en dieper op gang.",
      "120 blauwe LEDs doen dat werk. Kies op het display sensitive, medium of intensive, net wat je huid vandaag aankan.",
    ],
    minuten: "20 min",
    prijs: "19,50",
  },
  {
    slug: "ergoline-600-light",
    image: affinity600,
    imageQuality: 90,
    mobileVideo: "/videos/zonnebanken/ergoline-600-toggle-mobile.mp4?v=10",
    desktopVideo: "/videos/zonnebanken/ergoline-600-toggle-desktop.mp4?v=8",
    alt: "Ergoline Affinity 600 zonnebad",
    description: [
      "De rustigste bank van de vier. Fijn als je net begint of je huid liever langzaam laat wennen aan de zon.",
      "Verstelbare ligvlakken en armsteunen, plus ventilatie die de temperatuur aangenaam houdt. Je stapt er ontspannen weer uit.",
    ],
    minuten: "20 min",
    prijs: "12,00",
  },
];

export const ZONNEBANKEN: Zonnebank[] = BANKEN.map((bank) => ({
  ...bank,
  title: ZONNEBANK_BOOKINGS[bank.slug],
  whatsappUrl: zonnebankBookingUrl(bank.slug),
  qrCode: QR_CODES[bank.slug],
}));
